import { Divider } from "utils.slint";

export struct Event {
        summary: string,
        date: string,
        description: string,
        icon: image,
        background: color,
        textColor: color,
        descriptionColor: color,
}

component Headings {
    VerticalLayout {
        padding-bottom: 29px;
        spacing: 32px;
        Text {
            font-size: 4rem;
            height: 5rem;
            color: #FEFBE6;
            text: "Kalender";
        }

        Divider { }
    }
}

component EventCell {
    in property <Event> event: {
        summary: "Før timer Før timerFør timer Før timer Før timer",
        date: "31. April",
        description: "",
        icon: @image-url("../img/calendar/time.png"),
        background: #1F0D8D,
        textColor: #CFCFFF,
        descriptionColor: #CFCFFF80,
    };
    Rectangle {
        background: event.background;
        border-radius: 32px;
        // width: 628px;
        // height: 128px;
        HorizontalLayout {
            padding-top: 24px;
            padding-right: 32px;
            padding-bottom: 24px;
            padding-left: 32px;
            spacing: 32px;
            VerticalLayout {
                alignment: center;
                Image {
                    height: 3rem;
                    width: 3rem;
                    source: event.icon;
                }
            }

            VerticalLayout {
                alignment: center;
                spacing: 6px;
                // Må sette bredde for at clipping skal fungere
                // Bredde - ikon - padding høyre/venstre - spacing
                width: parent.width - 3rem - 3 * 32px;
                Text {
                    color: event.textColor;
                    font-size: 2.875rem;
                    text: event.summary;
                }

                Text {
                    color: event.textColor;
                    font-size: 2rem;
                    text: event.date;
                }

                if event.description != "": Text {
                    color: event.descriptionColor;
                    font-size: 1.5rem;
                    text: event.description;
                }
            }
        }
    }
}

component EventStack {
    in property <[Event]> events;
    in property <string> empty-text;
    if (events.length == 0): Text {
        font-size: 2rem;
        horizontal-alignment: center;
        color: #FEFBE6;
        text: empty-text;
        y: 0;
    }
    if (events.length > 0): VerticalLayout {
        spacing: 24px;
        alignment: start;
        for event in events: EventCell {
            event: event;
        }
    }
}

export component CalendarWidget {
    in property <[Event]> events: [
        {
            summary: "Lønningspils",
            date: "31. april",
            description: "",
            icon: @image-url("../img/calendar/time.png"),
            background: #1F0D8D,
            textColor: #CFCFFF,
            descriptionColor: #CFCFFF80,
        },
        {
            summary: "Før timer",
            date: "31. april",
            description: "",
            icon: @image-url("../img/calendar/time.png"),
            background: #1F0D8D,
            textColor: #CFCFFF,
            descriptionColor: #CFCFFF80,
        }
    ];
    VerticalLayout {
        alignment: start;
        padding-top: 1rem;
        Headings { }

        HorizontalLayout {
            height: 460px;
            EventStack {
                empty-text: "Ingenting planlagt for øyeblikket";
                events: events;
            }
        }
    }
}
