import { Button, VerticalBox } from "std-widgets.slint";

import { GridBox , HorizontalBox} from "std-widgets.slint";
import { ForecastWidget, Forecast } from "forecastwidget.slint";
import { FoodTrackerWidget, FoodTracking} from "foodtrackerwidget.slint";
import { StopPlaceData, TransportationWidget } from "transportation.slint";
import { CalendarWidget, Event } from "calendarwidget.slint";

import "./assets/FiraMono-Regular.ttf";
import "./assets/mergedfont.ttf";
import { SeasonEffects, Snowflake, SpookyFace, Bat } from "seasons.slint";

export component MainWindow inherits Window {
    in property <string> time: "12:34";
    in property <string> date: "Mandag 5. august";
    in property <Forecast> nowForecast: {
        temp: "-1",
        precipitation: "2",
        icon: @image-url("../img/weather/partlycloudy_day.png")
    };
    in property <Forecast> tomorrowForecast: {
        temp: "-1",
        precipitation: "2",
        icon: @image-url("../img/weather/partlycloudy_day.png")
    };
    in property <FoodTracking> foodTracking: {
        active: false,
        resturant_name: "McDonalds",
        minutes_remaining: "5",
    };

    in property <[Event]> events: [{
        summary: "Placeholder calendar event",
        date: "31. April",
        description: "",
        location: "",
        icon: @image-url("../img/calendar/time.png"),
        background: #1F0D8D,
        textColor: #CFCFFF,
        descriptionColor: #CFCFFF80,
    }];

    in property <[Snowflake]> snowflakes;
    in-out property <SpookyFace> spooky_face;
    in-out property <Bat> bat;

    in property <[[StopPlaceData]]> stopPlacesData: [
        [
            {
                stopName: "Placeholder",
                stopDataRows: [
                    {
                        transportMode: @image-url("../img/transport/walk.png"),
                        publicCode: 0,
                        destinationFrontText: "Månen",
                        departureTime: "Nå",
                        realtime: false,
                    }
                ]
            }
        ]
    ];

    in property <int> name;

    title: "Infoskjerm";
    //TODO: Set programmatically?
    no-frame: true;
    //width: 1080px;
    height: 1900px;
    background: #0C0C27;

    default-font-family: "Bagoss";

    SeasonEffects {
        snow: snowflakes;
        spooky_face: spooky_face;
        bat: bat;

        VerticalLayout {
            width: 100%;
            padding: 3rem;
            spacing: 4rem;
            alignment: start;
            HorizontalLayout {
                width: 100%;
                alignment: space-between;
                Text {
                    font-size: 2.5rem;
                    color: #FEFBE6;
                    text: date;
                }

                Text {
                    color: #FEFBE6;
                    font-size: 2.5rem;
                    text: time;
                }
            }

            ForecastWidget {
                now: nowForecast;
                tomorrow: tomorrowForecast;
            }

            if foodTracking.active: FoodTrackerWidget {
                tracking: foodTracking;
            }
            CalendarWidget {
                events: events;
            }

            TransportationWidget {
                stopPlacesData: stopPlacesData;
            }
        }
    }
}
